apiVersion: v2
name: ett-frontend
description: A Helm chart for Kubernetes

type: application
version: v0.1.1

dependencies:
  - name: ett-base-helm-chart
    version: 'v0.1.8'
    repository: 'https://energy-track-and-trace.github.io/helm-charts/'
