apiVersion: v2
name: eo-frontend
description: A Helm chart for Kubernetes

type: application
version: v0.1.1

dependencies:
  - name: eo-base-helm-chart
    version: 'v0.3.1'
    repository: 'https://energinet-datahub.github.io/helm-charts/'
