apiVersion: v2
name: eo-frontend
description: A Helm chart for Kubernetes

type: application
version: 0.2.13

dependencies:
  - name: eo-base-helm-chart
    version: 'v0.4.7'
    repository: 'https://energinet-datahub.github.io/helm-charts/'
