eo-base-helm-chart:
  deployments:
    app:
      replicaCount: 2
      image:
        repository: ghcr.io/energinet-datahub/eo-frontend-app
        tag: 0.2.6
  service:
    deployment: app
    type: ClusterIP
    port: 80

  ingress:
    hosts: []
    paths:
      - /
    pathExceptions:
      - /api
      - /auth
    servicePort: 80
