# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI orchestrator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # Markdown check and YAML validation
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v12
    with:
      skip_license_check: true # Handled by another workflow
      skip_markdown_links_check: true # Handled by another workflow
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN_REPO_WORKFLOW }}

  #
  # CodeQL Check
  #
  ci_codeql:
    uses: ./.github/workflows/codeql.yml

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml

  #
  # DataHub UI
  #
  dh_ci_frontend:
    needs: changes
    if: ${{ needs.changes.outputs.dh_frontend == 'true' || needs.changes.outputs.dh_frontend_e2e == 'true' }}
    uses: ./.github/workflows/dh-ci-frontend.yml
    secrets: inherit

  dh_ci_dotnet:
    needs: changes
    if: ${{ needs.changes.outputs.dh_dotnet == 'true' }}
    uses: ./.github/workflows/dh-ci-dotnet.yml
    secrets: inherit

  #
  # Watt
  #
  watt_ci:
    needs: changes
    if: ${{ needs.changes.outputs.watt_frontend == 'true' }}
    uses: ./.github/workflows/watt-ci.yml
    secrets: inherit

  #
  # C4 model
  #
  render_c4model_views:
    needs: changes
    if: ${{ needs.changes.outputs.render_c4model_views == 'true' }}
    uses: Energinet-DataHub/.github/.github/workflows/structurizr-render-diagrams.yml@v12
    with:
      structurizr_workspace_filename: views
      included_model_filename: model
    secrets:
      pat_token_retrigger_workflow: ${{ secrets.pat_token_repo_workflow }}

  #
  # Branch policy status check
  #
  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs:
      [
        ci_base,
        ci_codeql,
        dh_ci_frontend,
        dh_ci_dotnet,
        watt_ci,
        render_c4model_views
      ]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
            echo "Failed"
            exit 1
          fi
