# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Infrastructure CD

on:
  push:
    branches:
      - main
    paths:
      - build/infrastructure/**
      - build/modules/**
      - .github/workflows/infrastructure-cd.yml
  workflow_dispatch: {}
env:
  ORGANISATION_NAME: endk
  PROJECT_NAME: TEMPLATE_REPLACE__YOUR_DOMAIN_NAME_LOWERCASE_NO_SYMBOLS

jobs:
  infra_deploy:
    name: Deploy infrastructure to ${{ matrix.environment.long }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [
          {
            long: rg-DataHub-TEMPLATE_REPLACE__YOUR_DOMAIN_NAME-U,
            short: u,
            name: Development
          },
          {
            long: rg-DataHub-TEMPLATE_REPLACE__YOUR_DOMAIN_NAME-T,
            short: t,
            name: Test
          },
          {
            long: rg-DataHub-TEMPLATE_REPLACE__YOUR_DOMAIN_NAME-B,
            short: b,
            name: Preprod
          },
          {
            long: rg-DataHub-TEMPLATE_REPLACE__YOUR_DOMAIN_NAME-P,
            short: p,
            name: Production
          }
        ]
    environment:
      name: ${{ matrix.environment.long }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Secrets
        run: |  
          echo "ARM_TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.SPN_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_OBJECT_ID=${{ secrets.SPN_OBJECT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.SPN_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Azure CLI Install and Login
        uses: ./.github/actions/azure-cli-install-login


      - name: Setup Authorization to pull TF modules
        run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://foo:${{ secrets.PAT_TOKEN }}@github.com/Energinet-DataHub/geh-terraform-modules".insteadOf "https://github.com/Energinet-DataHub/geh-terraform-modules"
      
      - name: Check If Terraform State Storage exists
        id: state-storage-exists
        run: |
          storage_exists=$(az storage account check-name --name 'tfstate${{ env.PROJECT_NAME }}${{ matrix.environment.short }}' | python3 -c "import sys, json; print(not json.load(sys.stdin)['nameAvailable'])")
          echo "::set-output name=state-storage-exists::${storage_exists}"

      # Create TF State Container if needed
      - name: Create Terraform State Storage
        run: |
          storage_name="tfstate${{ env.PROJECT_NAME }}${{ matrix.environment.short }}"
          az storage account create --resource-group ${{ matrix.environment.long }} --name $storage_name --sku Standard_LRS --encryption-services blob
          account_key=$(az storage account keys list --resource-group ${{ matrix.environment.long }} --account-name $storage_name --query '[0].value' -o tsv)
          az storage container create --name tfstate --account-name $storage_name --account-key $account_key
        if: steps.state-storage-exists.outputs.state-storage-exists == 'False'

      # Try not to reference TF_VAR variables in pipeline yml files, only values should be set and they should be read in terraform only
      # rather create duplicate ENV pipeline vatiable if needed to separate concerns
      - name: Set TF Vars
        run: |
          echo "TF_VAR_environment=${{ matrix.environment.short }}" >> $GITHUB_ENV
          echo "TF_VAR_organisation=${{ env.ORGANISATION_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_project=${{ env.PROJECT_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_resource_group_name=${{ matrix.environment.long }}" >> $GITHUB_ENV

      - name: Configure Terraform Backend
        uses: ./.github/actions/configure-terraform-backend
        with:
          backend-file-path: "./build/infrastructure/backend.tf"
          resource-group-name: "${{ matrix.environment.long }}"
          storage-account-name: "tfstate${{ env.PROJECT_NAME }}${{ matrix.environment.short }}"

      - name: Terraform Init
        working-directory: ./build/infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: ./build/infrastructure
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./build/infrastructure
        run: terraform apply -no-color -auto-approve
        continue-on-error: false